// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class AccessMenubyRoleIdReturnModel
    {
        public System.Int32 Id { get; set; }
        public System.Int32 RoleId { get; set; }
        public System.Boolean IsActive { get; set; }
        public System.Int32 menuId { get; set; }
        public System.String Tittle { get; set; }
        public System.Int32 ParentId { get; set; }
        public System.String Controller { get; set; }
        public System.String Action { get; set; }
        public System.Boolean IsActive1 { get; set; }
        public System.Int16 AccessLevelId { get; set; }
    }

}
// </auto-generated>
