// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    // AppMenu
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class AppMenu : Entity
    {
        public int Id { get; set; } // Id (Primary key)
        public string Title { get; set; } // Title (length: 50)
        public int ParentId { get; set; } // ParentId
        public bool IsActive { get; set; } // IsActive
        public string NavImg { get; set; } // NavImg (length: 255)
        public string TitleUrdu { get; set; } // TitleUrdu (length: 255)
        public string TitleSindhi { get; set; } // TitleSindhi (length: 255)

        public AppMenu()
        {
            IsActive = true;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
