// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    // AssignRoleToProject
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class AssignRoleToProject : Entity
    {
        public int Id { get; set; } // Id (Primary key)
        public int? ProjectId { get; set; } // ProjectId
        public string RoleId { get; set; } // RoleId (length: 128)
        public System.DateTime CreatedAt { get; set; } // created_at
        public bool IsActive { get; set; } // IsActive

        // Foreign keys

        /// <summary>
        /// Parent AspNetRole pointed by [AssignRoleToProject].([RoleId]) (FK_AssignRoleToProject_AspNetRoles)
        /// </summary>
        public virtual AspNetRole AspNetRole { get; set; } // FK_AssignRoleToProject_AspNetRoles

        /// <summary>
        /// Parent ProjectSolution pointed by [AssignRoleToProject].([ProjectId]) (FK_AssignRoleToProject_ProjectSolution)
        /// </summary>
        public virtual ProjectSolution ProjectSolution { get; set; } // FK_AssignRoleToProject_ProjectSolution

        public AssignRoleToProject()
        {
            CreatedAt = System.DateTime.Now;
            IsActive = true;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
