// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    // Blmis_userstock
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class BlmisUserstock : Entity
    {
        public int Id { get; set; } // Id (Primary key)
        public int UserId { get; set; } // UserId
        public int ProductId { get; set; } // ProductId
        public int Quantity { get; set; } // Quantity
        public decimal Price { get; set; } // Price
        public System.DateTime CreatedAt { get; set; } // created_at
        public bool IsActive { get; set; } // IsActive
        public int? LhvId { get; set; } // LhvId
        public string CategoryId { get; set; } // CategoryId (length: 50)
        public System.DateTime? Date { get; set; } // date
        public int? ProjectId { get; set; } // ProjectId
        public string Unit { get; set; } // Unit (length: 255)

        public BlmisUserstock()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
