// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    // categories
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class Category : Entity
    {
        public int CategoryId { get; set; } // category_id (Primary key)
        public string CategoryName { get; set; } // category_name (length: 255)
        public string CategoryNameSindhi { get; set; } // category_name_sindhi (length: 255)
        public string CategoryNameUrdu { get; set; } // category_name_urdu (length: 255)
        public System.DateTime CreatedAt { get; set; } // created_at
        public bool IsActive { get; set; } // isActive
        public int? ProjectId { get; set; } // ProjectId

        public Category()
        {
            CreatedAt = System.DateTime.Now;
            IsActive = true;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
