// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    // content
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class ContentConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Content>
    {
        public ContentConfiguration()
            : this("dbo")
        {
        }

        public ContentConfiguration(string schema)
        {
            ToTable("content", schema);
            HasKey(x => x.ContentId);

            Property(x => x.ContentId).HasColumnName(@"content_id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.ContentName).HasColumnName(@"content_name").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.ContentNameSindhi).HasColumnName(@"content_name_sindhi").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.ContentNameUrdu).HasColumnName(@"content_name_urdu").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.Path).HasColumnName(@"path").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.PathSindhi).HasColumnName(@"path_sindhi").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.PathUrdu).HasColumnName(@"path_urdu").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.CategoryId).HasColumnName(@"category_id").HasColumnType("int").IsRequired();
            Property(x => x.ContentType).HasColumnName(@"content_type").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.Thumbnail).HasColumnName(@"thumbnail").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.CreatedAt).HasColumnName(@"created_at").HasColumnType("datetime2").IsRequired();
            Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit").IsRequired();
            Property(x => x.ProjectId).HasColumnName(@"ProjectId").HasColumnType("int").IsOptional();
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
