// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    // Devices
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class Device : Entity
    {
        public int Id { get; set; } // Id (Primary key)
        public string MacAddress { get; set; } // MAC_Address (length: 200)
        public string DeviceId { get; set; } // DeviceId (length: 200)
        public string DeviceToken { get; set; } // DeviceToken (length: 1000)
        public short DeviceType { get; set; } // DeviceType
        public string VersionName { get; set; } // VersionName (length: 50)
        public string VersionCode { get; set; } // VersionCode (length: 50)
        public int? UserId { get; set; } // UserId
        public bool IsActive { get; set; } // IsActive

        public Device()
        {
            IsActive = true;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
