// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class GetAllLogwithNameReturnModel
    {
        public System.Int32 log_id { get; set; }
        public System.String description { get; set; }
        public System.String user_type { get; set; }
        public System.Int32 user_id { get; set; }
        public System.String full_name { get; set; }
        public System.DateTime created_at { get; set; }
        public System.String Duration { get; set; }
        public System.Boolean? IsComplete { get; set; }
        public System.Boolean IsActive { get; set; }
    }

}
// </auto-generated>
