// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class GetDashboardcountReturnModel
    {
        public System.Int32? Mawra { get; set; }
        public System.Int32? NoorWorker { get; set; }
        public System.Int32? LHV { get; set; }
        public System.Int32? TotalClients { get; set; }
        public System.Int32? ContinuedUserClient { get; set; }
        public System.Int32? NewUserClient { get; set; }
        public System.Int32? DropOutClient { get; set; }
    }

}
// </auto-generated>
