// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class GetMwraClienNametByMwraIdReturnModel
    {
        public System.Int32 mwra_client_id { get; set; }
        public System.String foul { get; set; }
        public System.String pain_lower { get; set; }
        public System.String referral { get; set; }
        public System.String history { get; set; }
        public System.String contraceptual { get; set; }
        public System.String date_of_starting { get; set; }
        public System.String weight { get; set; }
        public System.String lmp_date { get; set; }
        public System.String date_of_client_generation { get; set; }
        public System.String bp { get; set; }
        public System.String jaundice { get; set; }
        public System.String occasional { get; set; }
        public System.String polar_anemia { get; set; }
        public System.Int32? mwra_id { get; set; }
        public System.Int32? ProductId { get; set; }
        public System.Int32? Quantity { get; set; }
        public System.String product_name { get; set; }
        public System.String mwra { get; set; }
        public System.DateTime? created_at { get; set; }
        public System.String mwcode { get; set; }
        public System.String longitude { get; set; }
        public System.String latitude { get; set; }
        public System.String fpmethod { get; set; }
        public System.String nextfollowupdate { get; set; }
        public System.Boolean IsActive { get; set; }
    }

}
// </auto-generated>
