// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class GetNoorClientCheckListingReturnModel
    {
        public System.Int32 noor_checklist_id { get; set; }
        public System.Int32 app_user_id { get; set; }
        public System.DateTime created_at { get; set; }
        public System.String noor_markaz_renovated { get; set; }
        public System.String sign_boards { get; set; }
        public System.String examination_couch { get; set; }
        public System.String plastic_sheet { get; set; }
        public System.String light { get; set; }
        public System.String privacy_assurance { get; set; }
        public System.String posters { get; set; }
        public System.String sac_banner { get; set; }
        public System.String remarks1 { get; set; }
        public System.String worker_bag_available { get; set; }
        public System.String phone_charger_available { get; set; }
        public System.String speakers_available { get; set; }
        public System.String mwra_booklet_available { get; set; }
        public System.String tracking_cards_available { get; set; }
        public System.String WorkerBagFunctional { get; set; }
        public System.String phone_charger_func { get; set; }
        public System.String speakers_func { get; set; }
        public System.String mwra_booklet_func { get; set; }
        public System.String tracking_cards_func { get; set; }
        public System.String remarks2 { get; set; }
        public System.String pills { get; set; }
        public System.String condoms { get; set; }
        public System.String remarks3 { get; set; }
        public System.String washing_soap { get; set; }
        public System.String detergent { get; set; }
        public System.String hand_wash { get; set; }
        public System.String bath_soap { get; set; }
        public System.String sanitary_napkins { get; set; }
        public System.String toothpaste { get; set; }
        public System.String tooth_brush { get; set; }
        public System.String dettol { get; set; }
        public System.String slippers { get; set; }
        public System.String school_shoes_girls { get; set; }
        public System.String school_shoes_boys { get; set; }
        public System.String new_born_kits { get; set; }
        public System.String cloths { get; set; }
        public System.String pulses { get; set; }
        public System.String rice { get; set; }
        public System.String sugar { get; set; }
        public System.String vegetable_edible_oil { get; set; }
        public System.String eggs { get; set; }
        public System.String flour { get; set; }
        public System.String lodized_salt { get; set; }
        public System.String syp_paracetamol { get; set; }
        public System.String tab_paracetamol { get; set; }
        public System.String syp_amoxil { get; set; }
        public System.String cap_amoxil { get; set; }
        public System.String ors { get; set; }
        public System.String tab_folic_acid { get; set; }
        public System.String iron_tablets { get; set; }
        public System.String multi_vitamin { get; set; }
        public System.String tab_metronidazole { get; set; }
        public System.String syp_metronidazole { get; set; }
        public System.String polyfax_skin { get; set; }
        public System.String saniplast { get; set; }
        public System.String remarks4 { get; set; }
        public System.String total_purchase_last_month { get; set; }
        public System.String total_sale_last_month { get; set; }
        public System.String remarks5 { get; set; }
        public System.String amount_received_last_stipend { get; set; }
        public System.String month_received_last_stipend { get; set; }
        public System.String problem_receiving_stipend { get; set; }
        public System.String remarks6 { get; set; }
        public System.String number_of_hh { get; set; }
        public System.String number_of_visits_last_month { get; set; }
        public System.String remarks7 { get; set; }
        public System.String health_committee { get; set; }
        public System.String num_hc_members { get; set; }
        public System.String monthly_meeting { get; set; }
        public System.String remarks8 { get; set; }
        public System.String fp_method_pills { get; set; }
        public System.String fp_method_condoms { get; set; }
        public System.String fp_method_injectables { get; set; }
        public System.String fp_method_iucd { get; set; }
        public System.String fp_method_tl { get; set; }
        public System.String fp_method_implant { get; set; }
        public System.String know_appropriate_facility { get; set; }
        public System.String know_location_uc_hcp { get; set; }
        public System.String enlist_enroll_mwra { get; set; }
        public System.String space_provide_noor_markaz { get; set; }
        public System.String conduct_councel { get; set; }
        public System.String conduct_family_session { get; set; }
        public System.String enlist_potential_clients { get; set; }
        public System.String facilitate_lhv_arranging_clinic { get; set; }
        public System.String fp_supplies_condoms { get; set; }
        public System.String followup_clients_through_cards { get; set; }
        public System.String inform_lhv_if_side_effect { get; set; }
        public System.String reassure_till_lhv_arrives { get; set; }
        public System.String facilitate_lhv_maintain { get; set; }
        public System.String manage_hygiene_products { get; set; }
        public System.String social_market_promotions { get; set; }
        public System.String keep_sale_record { get; set; }
        public System.String with_lhv_support { get; set; }
        public System.String conduct_muac_for_plw { get; set; }
        public System.String conduct_muac_for_children { get; set; }
        public System.String SupportGroupFormation { get; set; }
        public System.String remarks9 { get; set; }
        public System.String know_session_on_mobile { get; set; }
        public System.String mazbot_bandi { get; set; }
        public System.String sehat_khushi { get; set; }
        public System.String sahi_waqt_sahi_faisla { get; set; }
        public System.String khandani_mansoba_bandi { get; set; }
        public System.String khandani_mansoba_kadeem { get; set; }
        public System.String bachon_ki_pedaish { get; set; }
        public System.String mustaqil_tariqay { get; set; }
        public System.String khawateen_iucd { get; set; }
        public System.String khandani_mansoba_bandi_tikay { get; set; }
        public System.String khandani_mansoba_bandi_implant { get; set; }
        public System.String khandani_mansoba_bandi_sawalat { get; set; }
        public System.String remarks10 { get; set; }
        public System.Int32? lhv_id { get; set; }
        public System.String visitor_name { get; set; }
        public System.String date { get; set; }
        public System.Int32? visitor_id { get; set; }
        public System.Boolean IsActive { get; set; }
        public System.Int32? ProjectId { get; set; }
    }

}
// </auto-generated>
