// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    // InventoryReturns
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class InventoryReturn : Entity
    {
        public int Id { get; set; } // Id (Primary key)
        public int? UserId { get; set; } // userId
        public string UserType { get; set; } // UserType (length: 50)
        public int? ProductId { get; set; } // ProductId
        public int? Quantity { get; set; } // Quantity
        public int? ReturnType { get; set; } // ReturnType
        public string Description { get; set; } // Description (length: 500)
        public System.DateTime? CreatedAt { get; set; } // created_at
        public bool IsActive { get; set; } // IsActive
        public int? ProjectId { get; set; } // ProjectId
        public int? RegionId { get; set; } // RegionId

        public InventoryReturn()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
