// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    // lhv_checklist
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class LhvChecklistConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<LhvChecklist>
    {
        public LhvChecklistConfiguration()
            : this("dbo")
        {
        }

        public LhvChecklistConfiguration(string schema)
        {
            ToTable("lhv_checklist", schema);
            HasKey(x => x.LhvChecklistId);

            Property(x => x.LhvChecklistId).HasColumnName(@"lhv_checklist_id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.AppUserId).HasColumnName(@"app_user_id").HasColumnType("int").IsRequired();
            Property(x => x.VisitorId).HasColumnName(@"visitor_id").HasColumnType("int").IsRequired();
            Property(x => x.VisitorName).HasColumnName(@"visitor_name").HasColumnType("nvarchar").IsRequired().HasMaxLength(255);
            Property(x => x.CreatedAt).HasColumnName(@"created_at").HasColumnType("datetime2").IsRequired();
            Property(x => x.IucdInsertionKit).HasColumnName(@"iucd_insertion_kit").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.MuacTape).HasColumnName(@"muac_tape").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.MeasuringTape).HasColumnName(@"measuring_tape").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.Stethoscope).HasColumnName(@"stethoscope").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.BpApparatus).HasColumnName(@"bp_apparatus").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.WeighingMachcine).HasColumnName(@"weighing_machcine").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.Fetoscope).HasColumnName(@"fetoscope").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.Thermometer).HasColumnName(@"thermometer").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.InfectionPreventionKit).HasColumnName(@"infection_prevention_kit").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.TabletWithCharger).HasColumnName(@"tablet_with_charger").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.DangerBox).HasColumnName(@"danger_box").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.LhvApron).HasColumnName(@"lhv_apron").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.MecWheel).HasColumnName(@"mec_wheel").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.IucdInsertionKitFunc).HasColumnName(@"iucd_insertion_kit_func").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.BpApparatusFunc).HasColumnName(@"bp_apparatus_func").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.WeighingFunc).HasColumnName(@"weighing_func").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.ThermometerFunc).HasColumnName(@"thermometer_func").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.InfectionPreventionKitFunc).HasColumnName(@"infection_prevention_kit_func").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.TabletWithChargerFunc).HasColumnName(@"tablet_with_charger_func").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.DangerBoxFunc).HasColumnName(@"danger_box_func").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.LhvApronFunc).HasColumnName(@"lhv_apron_func").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.ProvideCounselingAboutFp).HasColumnName(@"provide_counseling_about_fp").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.OralPills).HasColumnName(@"oral_pills").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.Injections).HasColumnName(@"injections").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.Iud).HasColumnName(@"iud").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.Condoms).HasColumnName(@"condoms").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.Implant).HasColumnName(@"implant").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.AnyNaturalMethod).HasColumnName(@"any_natural_method").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.PermanentMethod).HasColumnName(@"permanent_method").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.AnyOther).HasColumnName(@"any_other").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.ProviderUseMecWheel).HasColumnName(@"provider_use_mec_wheel").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.CheckBp).HasColumnName(@"check_bp").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.CheckAnemiaAndJaundice).HasColumnName(@"check_anemia_and_jaundice").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.MeasurementOfWeight).HasColumnName(@"measurement_of_weight").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.PelvicExam).HasColumnName(@"pelvic_exam").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.ClientReceiveMethodChoice).HasColumnName(@"client_receive_method_choice").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.ExplainHowToUse).HasColumnName(@"explain_how_to_use").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.AboutPossibleSideEffects).HasColumnName(@"about_possible_side_effects").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.ExperienceSideEffect).HasColumnName(@"experience_side_effect").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.FollowUp).HasColumnName(@"follow_up").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.GiveTrackingCard).HasColumnName(@"give_tracking_card").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.TotalNumOfMwras).HasColumnName(@"total_num_of_mwras").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.HowManyVerifiedByTeam).HasColumnName(@"how_many_verified_by_team").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.Remarks1).HasColumnName(@"remarks1").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.Date).HasColumnName(@"date").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(20);
            Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit").IsRequired();
            Property(x => x.ProjectId).HasColumnName(@"ProjectId").HasColumnType("int").IsOptional();
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
