// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    // mwra
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class MwraConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Mwra>
    {
        public MwraConfiguration()
            : this("dbo")
        {
        }

        public MwraConfiguration(string schema)
        {
            ToTable("mwra", schema);
            HasKey(x => x.MwraId);

            Property(x => x.MwraId).HasColumnName(@"mwra_id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Name).HasColumnName(@"name").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.Dob).HasColumnName(@"dob").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.Address).HasColumnName(@"address").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.ContactNumber).HasColumnName(@"contact_number").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(25);
            Property(x => x.AssignedMarviId).HasColumnName(@"assigned_marvi_id").HasColumnType("int").IsRequired();
            Property(x => x.Longitude).HasColumnName(@"longitude").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(20);
            Property(x => x.Latitude).HasColumnName(@"latitude").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(20);
            Property(x => x.HusbandName).HasColumnName(@"husband_name").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.Cnic).HasColumnName(@"cnic").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.MaritialStatus).HasColumnName(@"maritial_status").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(100);
            Property(x => x.Age).HasColumnName(@"age").HasColumnType("int").IsOptional();
            Property(x => x.Occupation).HasColumnName(@"occupation").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.IsClient).HasColumnName(@"is_client").HasColumnType("smallint").IsOptional();
            Property(x => x.CreatedAt).HasColumnName(@"created_at").HasColumnType("datetime2").IsOptional();
            Property(x => x.RegionId).HasColumnName(@"region_id").HasColumnType("int").IsOptional();
            Property(x => x.TaluqaId).HasColumnName(@"taluqa_id").HasColumnType("int").IsOptional();
            Property(x => x.UnionCouncilId).HasColumnName(@"union_council_id").HasColumnType("int").IsOptional();
            Property(x => x.EducationOfClass).HasColumnName(@"education_of_class").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.DurationOfMarriage).HasColumnName(@"duration_of_marriage").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.CrrentlyPregnant).HasColumnName(@"crrently_pregnant").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.PregnantNoOfMonths).HasColumnName(@"pregnant_no_of_months").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.NoOfAliveChildren).HasColumnName(@"no_of_alive_children").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.NoOfAbortion).HasColumnName(@"no_of_abortion").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.NoOfChildrenDied).HasColumnName(@"no_of_children_died").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.ReasonOfDeath).HasColumnName(@"reason_of_death").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.AgeOfYoungestChildYears).HasColumnName(@"age_of_youngest_child_years").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.AgeOfYoungestChildMonths).HasColumnName(@"age_of_youngest_child_months").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.HaveUsedFpMethod).HasColumnName(@"have_used_fp_method").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.NameOfFp).HasColumnName(@"name_of_fp").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.FpNotUsedInYears).HasColumnName(@"fp_not_used_in_years").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.ReasonOfDiscontinuation).HasColumnName(@"reason_of_discontinuation").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.FpNoReason).HasColumnName(@"fp_no_reason").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.WantToUseFp).HasColumnName(@"want_to_use_fp").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.FpPurpose).HasColumnName(@"fp_purpose").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.IsUserFp).HasColumnName(@"is_user_fp").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.FpMethodUsed).HasColumnName(@"fp_method_used").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.DateOfRegistration).HasColumnName(@"date_of_registration").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.DropoutDate).HasColumnName(@"DropoutDate").HasColumnType("datetime2").IsOptional();
            Property(x => x.DropoutReason).HasColumnName(@"DropoutReason").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit").IsRequired();
            Property(x => x.ProjectId).HasColumnName(@"ProjectId").HasColumnType("int").IsOptional();
            Property(x => x.DeviceCreatedDate).HasColumnName(@"DeviceCreatedDate").HasColumnType("datetime2").IsOptional();
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
