// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    // The table 'Mwra_ppif_delme' is not usable by entity framework because it
    // does not have a primary key. It is listed here for completeness.
    // Mwra_ppif_delme
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class MwraPpifDelme : Entity
    {
        public System.DateTime? DateOfRegistration { get; set; } // date_of_registration
        public string FullName { get; set; } // full_name (length: 255)
        public string Address { get; set; } // address (length: 255)
        public string UnionCouncilName { get; set; } // union_council_name (length: 255)
        public string RegionName { get; set; } // region_name (length: 255)
        public string TaluqaName { get; set; } // taluqa_name (length: 255)
        public string Name { get; set; } // name (length: 255)
        public string HusbandName { get; set; } // husband_name (length: 255)
        public double? Cnic { get; set; } // cnic
        public double? ContactNumber { get; set; } // contact_number
        public double? EducationOfClass { get; set; } // education_of_class
        public string Occupation { get; set; } // occupation (length: 255)
        public double? Dob { get; set; } // dob
        public double? Age { get; set; } // age
        public double? DurationOfMarriage { get; set; } // duration_of_marriage
        public string CrrentlyPregnant { get; set; } // crrently_pregnant (length: 255)
        public double? NoOfAliveChildren { get; set; } // no_of_alive_children
        public string NoOfAbortion { get; set; } // no_of_abortion (length: 255)
        public double? NoOfChildrenDied { get; set; } // no_of_children_died
        public string ReasonOfDeath { get; set; } // reason_of_death (length: 255)
        public string AgeOfYoungestChildYears { get; set; } // age_of_youngest_child_years (length: 255)
        public double? AgeOfYoungestChildMonths { get; set; } // age_of_youngest_child_months
        public string HaveUsedFpMethod { get; set; } // have_used_fp_method (length: 255)
        public string NameOfFp { get; set; } // name_of_fp (length: 255)
        public string FpNotUsedInYears { get; set; } // fp_not_used_in_years (length: 255)
        public string ReasonOfDiscontinuation { get; set; } // reason_of_discontinuation (length: 255)
        public string FpNoReason { get; set; } // fp_no_reason (length: 255)
        public string WantToUseFp { get; set; } // want_to_use_fp (length: 255)
        public string FpPurpose { get; set; } // fp_purpose (length: 255)
        public string IsUserFp { get; set; } // is_user_fp (length: 255)
        public string FpMethodUsed { get; set; } // fp_method_used (length: 255)
        public int? MarviId { get; set; } // MarviId
        public int? Talukaid { get; set; } // talukaid
        public int? Ucid { get; set; } // Ucid

        public MwraPpifDelme()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
