// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    // mwra_categories
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class MwraCategoryConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<MwraCategory>
    {
        public MwraCategoryConfiguration()
            : this("dbo")
        {
        }

        public MwraCategoryConfiguration(string schema)
        {
            ToTable("mwra_categories", schema);
            HasKey(x => x.MwraId);

            Property(x => x.MwraId).HasColumnName(@"mwra_id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.CategoryId).HasColumnName(@"category_id").HasColumnType("int").IsRequired();
            Property(x => x.Isdefault).HasColumnName(@"isdefault").HasColumnType("smallint").IsRequired();
            Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit").IsRequired();
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
