// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    // The table 'NewMwra_Delme' is not usable by entity framework because it
    // does not have a primary key. It is listed here for completeness.
    // NewMwra_Delme
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class NewMwraDelme : Entity
    {
        public double? S35 { get; set; } // S#
        public System.DateTime? DateOfRegistration { get; set; } // Date of Registration
        public string NwCode { get; set; } // NW Code (length: 255)
        public string NameOfNoorWorker { get; set; } // Name of Noor worker (length: 255)
        public string NoorId { get; set; } // NoorId (length: 255)
        public string NameOfVillage { get; set; } // Name of Village (length: 255)
        public string NameOfUc { get; set; } // Name of UC (length: 255)
        public int? Ucid { get; set; } // UCID
        public string NameOfTehsil { get; set; } // Name of Tehsil (length: 255)
        public int? Tid { get; set; } // TID
        public string NameOfMwra { get; set; } // Name of MWRA (length: 255)
        public string NameOfHusband { get; set; } // Name of Husband (length: 255)
        public string CnicNumber { get; set; } // CNIC Number (length: 255)
        public string ContactNumber { get; set; } // Contact Number (length: 255)
        public double? Education4035OfClassesAttended6101641 { get; set; } // Education (-# of classes attended = 0-16)
        public string Occupation { get; set; } // Occupation (length: 255)
        public double? YearOfBirth { get; set; } // Year of Birth
        public double? Age40InYears41OfMwrAs { get; set; } // Age (in Years) of MWRAs
        public double? DurationOfMarriage { get; set; } // Duration of Marriage
        public string CurrentlyPregnant { get; set; } // Currently Pregnant (length: 255)
        public string IfYes44ThenNo35OfMonths { get; set; } // If Yes, then No# of Months (length: 255)
        public double? No35OfAliveChildren { get; set; } // No# of Alive Children
        public string No35OfAbortions { get; set; } // No# of Abortions (length: 255)
        public string No35OfChildrenDied { get; set; } // No# of Children Died (length: 255)
        public string ReasonOfDeath { get; set; } // Reason of Death (length: 255)
        public string AgeOfYoungestChildIf62540Years41 { get; set; } // Age of youngest  Child if >5 (Years) (length: 255)
        public double? AgeOfYoungestChildIf60540Months41 { get; set; } // Age of youngest Child if     <5 (Months)
        public string HaveYouEverUsedFpMethod { get; set; } // Have you ever used FP method (length: 255)
        public string IfYes44ThenWriteNameOfFpMethod { get; set; } // If Yes, then write name of FP method (length: 255)
        public string SinceHowLongFpNotUsed40Years41 { get; set; } // Since how long FP not used (Years) (length: 255)
        public string ReasonForDiscontinuation { get; set; } // Reason for Discontinuation (length: 255)
        public string IfNo44AnyReason { get; set; } // If no, any reason (length: 255)
        public string DoYouWantToUseYes47No { get; set; } // Do you want to use        Yes / No (length: 255)
        public double? IfYesForWhichPurpose161Spacing261Limiting { get; set; } // If yes for which purpose         _1= Spacing_2= Limiting
        public string CurrentUserOfFp { get; set; } // Current User of FP (length: 255)
        public string IfCurrentUserThanWhichMethodIsUsing { get; set; } // If current user than which method is using (length: 255)
        public string CrCode { get; set; } // CR Code (length: 255)
        public System.DateTime? DateOfClientGeneration { get; set; } // Date of client generation
        public string Interval { get; set; } // Interval (length: 255)
        public string Postpartum { get; set; } // Postpartum (length: 255)
        public string PostAbortion { get; set; } // Post Abortion (length: 255)
        public string Ppfp { get; set; } // PPFP (length: 255)
        public string Pac { get; set; } // PAC (length: 255)
        public string NameOfReferralFacility47Hcp { get; set; } // Name of referral facility / HCP (length: 255)
        public string InCaseOfCurrentUser44DateOfStarting { get; set; } // In case of Current User, Date of Starting (length: 255)
        public string HistoryOfIrregularMenstrualCycleYes47No { get; set; } // History of Irregular Menstrual Cycle _Yes/No (length: 255)
        public System.DateTime? Lmp40Date41 { get; set; } // LMP (Date)
        public string Bp { get; set; } // BP (length: 255)
        public double? Weight { get; set; } // Weight
        public string JaundiceYes47No { get; set; } // Jaundice _Yes / No (length: 255)
        public string Pallor47AnemiaYes47No { get; set; } // Pallor / Anemia_Yes / No (length: 255)
        public string FoulSmellingVaginalDischargeYes47No { get; set; } // Foul smelling vaginal discharge_Yes / No (length: 255)
        public string PainLowerAbdomenYes47No { get; set; } // Pain Lower abdomen_Yes / No (length: 255)
        public string Pills { get; set; } // Pills (length: 255)
        public string Condomss { get; set; } // Condomss (length: 255)
        public string Injectables1Month { get; set; } // Injectables  1 month (length: 255)
        public string Injectables2Month { get; set; } // Injectables  2 month (length: 255)
        public string Injectables3Month { get; set; } // Injectables 3 month (length: 255)
        public string Iucd5Years { get; set; } // IUCD 5 years (length: 255)
        public string Iucd10Years { get; set; } // IUCD 10 years (length: 255)
        public string Implant { get; set; } // Implant (length: 255)
        public string Tl { get; set; } // TL (length: 255)

        public NewMwraDelme()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
