// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    // The table 'NoOfAliveChildren_Delme' is not usable by entity framework because it
    // does not have a primary key. It is listed here for completeness.
    // NoOfAliveChildren_Delme
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class NoOfAliveChildrenDelme : Entity
    {
        public string DateOfRegistration { get; set; } // Date Of Registration (length: 255)
        public string MwCode { get; set; } // MW Code (length: 255)
        public string NameOfMarviWorker { get; set; } // Name Of Marvi Worker (length: 255)
        public string Village { get; set; } // Village (length: 255)
        public string District { get; set; } // District (length: 255)
        public string Taluqa { get; set; } // Taluqa (length: 255)
        public string UnionCouncil { get; set; } // Union Council (length: 255)
        public string NameOfMwra { get; set; } // Name Of MWRA (length: 255)
        public string HusbandName { get; set; } // Husband Name (length: 255)
        public string CnicNo { get; set; } // CNIC No (length: 255)
        public string ContactNo { get; set; } // Contact No (length: 255)
        public string Education40OfClassAttended6101641 { get; set; } // Education(Of Class Attended = 0 - 16) (length: 255)
        public string Occupation { get; set; } // Occupation (length: 255)
        public string YearOfBirth { get; set; } // Year Of Birth (length: 255)
        public string Age40InYearOfMwrAs41 { get; set; } // Age(In Year Of MWRAs) (length: 255)
        public string DurationOfMarriage { get; set; } // Duration Of Marriage (length: 255)
        public string CurrentlyPregnant { get; set; } // Currently Pregnant (length: 255)
        public string NoOfMonth { get; set; } // No Of Month (length: 255)
        public string NoOfAliveChildern { get; set; } // No Of Alive Childern (length: 255)
        public string NoOfAbortion { get; set; } // No Of Abortion (length: 255)
        public string NoOfChildernDied { get; set; } // No Of Childern Died (length: 255)
        public string ReasonOfDeath { get; set; } // Reason Of Death (length: 255)
        public string AgeOfYoungestChildIf62540Years41 { get; set; } // Age Of Youngest Child If > 5(Years) (length: 255)
        public string AgeOfYoungestChildIf60540Months41 { get; set; } // Age Of Youngest Child If < 5(Months) (length: 255)
        public string HaveYouEverUsedFpMethod { get; set; } // Have You Ever Used FP Method (length: 255)
        public string NameOfFpMethod { get; set; } // Name Of FP Method (length: 255)
        public string SinceHowLongFpNotUsed40Years41 { get; set; } // Since How Long FP Not Used(Years) (length: 255)
        public string ReasonOfDiscontinuation { get; set; } // Reason Of Discontinuation (length: 255)
        public string FpNo44AnyReason { get; set; } // FP No, Any Reason (length: 255)
        public string DoYouWantToUseFpMethod { get; set; } // Do You Want To Use FP Method (length: 255)
        public string FpPurpose { get; set; } // FP Purpose (length: 255)
        public string CurrentUserOfFp { get; set; } // Current User Of FP (length: 255)
        public string NameOfFp { get; set; } // Name Of FP (length: 255)

        public NoOfAliveChildrenDelme()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
