// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    // roles
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class Role : Entity
    {
        public int RoleId { get; set; } // role_id (Primary key)
        public string RoleName { get; set; } // role_name (length: 255)
        public System.DateTime CreatedAt { get; set; } // created_at
        public bool IsActive { get; set; } // IsActive
        public int? ProjectId { get; set; } // ProjectId

        // Reverse navigation

        /// <summary>
        /// Child RoleMenuAccesses where [RoleMenuAccess].[RoleId] point to this entity (FK_RoleMenuAccess_roles)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<RoleMenuAccess> RoleMenuAccesses { get; set; } // RoleMenuAccess.FK_RoleMenuAccess_roles
        /// <summary>
        /// Child Users where [users].[role_id] point to this entity (FK_users_roles)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<User> Users { get; set; } // users.FK_users_roles

        public Role()
        {
            CreatedAt = System.DateTime.Now;
            IsActive = true;
            RoleMenuAccesses = new System.Collections.Generic.List<RoleMenuAccess>();
            Users = new System.Collections.Generic.List<User>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
