// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    // SessionInventory
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class SessionInventoryConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<SessionInventory>
    {
        public SessionInventoryConfiguration()
            : this("dbo")
        {
        }

        public SessionInventoryConfiguration(string schema)
        {
            ToTable("SessionInventory", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.SessionId).HasColumnName(@"SessionId").HasColumnType("int").IsOptional();
            Property(x => x.ProductId).HasColumnName(@"ProductId").HasColumnType("int").IsOptional();
            Property(x => x.Quantity).HasColumnName(@"Quantity").HasColumnType("int").IsOptional();
            Property(x => x.UserId).HasColumnName(@"UserId").HasColumnType("int").IsOptional();
            Property(x => x.MwraId).HasColumnName(@"MwraId").HasColumnType("int").IsOptional();
            Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit").IsRequired();
            Property(x => x.CreatedDate).HasColumnName(@"createdDate").HasColumnType("datetime2").IsRequired();
            Property(x => x.MwraClientId).HasColumnName(@"mwra_client_id").HasColumnType("int").IsOptional();
            Property(x => x.FollowupId).HasColumnName(@"FollowupId").HasColumnType("int").IsOptional();
            Property(x => x.ReturnId).HasColumnName(@"ReturnId").HasColumnType("int").IsOptional();
            Property(x => x.ProjectId).HasColumnName(@"projectId").HasColumnType("int").IsOptional();
            Property(x => x.RegionId).HasColumnName(@"RegionId").HasColumnType("int").IsOptional();
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
