// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    // session_mwras
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class SessionMwra : Entity
    {
        public int SessionMwraId { get; set; } // session_mwra_id (Primary key)
        public int SessionId { get; set; } // session_id
        public int MwraId { get; set; } // mwra_id
        public System.DateTime JoinDatetime { get; set; } // join_datetime
        public bool IsActive { get; set; } // IsActive
        public int? ProjectId { get; set; } // ProjectId
        public int? MwraCount { get; set; } // mwraCount

        public SessionMwra()
        {
            JoinDatetime = System.DateTime.Now;
            IsActive = true;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
