// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    // SessionContent
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class SessionContentConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<SessionContent>
    {
        public SessionContentConfiguration()
            : this("dbo")
        {
        }

        public SessionContentConfiguration(string schema)
        {
            ToTable("SessionContent", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.SessionId).HasColumnName(@"sessionId").HasColumnType("int").IsOptional();
            Property(x => x.ContentId).HasColumnName(@"contentId").HasColumnType("int").IsOptional();
            Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit").IsRequired();
            Property(x => x.ProjectId).HasColumnName(@"ProjectId").HasColumnType("int").IsOptional();

            // Foreign keys
            HasOptional(a => a.Content).WithMany(b => b.SessionContents).HasForeignKey(c => c.ContentId).WillCascadeOnDelete(false); // FK_SessionContent_content
            HasOptional(a => a.Session).WithMany(b => b.SessionContents).HasForeignKey(c => c.SessionId).WillCascadeOnDelete(false); // FK_SessionContent_session
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
