// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    // session_mwras
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class SessionMwraConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<SessionMwra>
    {
        public SessionMwraConfiguration()
            : this("dbo")
        {
        }

        public SessionMwraConfiguration(string schema)
        {
            ToTable("session_mwras", schema);
            HasKey(x => x.SessionMwraId);

            Property(x => x.SessionMwraId).HasColumnName(@"session_mwra_id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.SessionId).HasColumnName(@"session_id").HasColumnType("int").IsRequired();
            Property(x => x.MwraId).HasColumnName(@"mwra_id").HasColumnType("int").IsRequired();
            Property(x => x.JoinDatetime).HasColumnName(@"join_datetime").HasColumnType("datetime2").IsRequired();
            Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit").IsRequired();
            Property(x => x.ProjectId).HasColumnName(@"ProjectId").HasColumnType("int").IsOptional();
            Property(x => x.MwraCount).HasColumnName(@"mwraCount").HasColumnType("int").IsOptional();
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
