// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class SpBlmisSellsReturnModel
    {
        public System.Int32 Id { get; set; }
        public System.Int32? ProjectId { get; set; }
        public System.String SellDate { get; set; }
        public System.String TotalSells { get; set; }
        public System.Decimal? TotalSellsInt { get; set; }
        public System.DateTime? YesterdaySellDate { get; set; }
        public System.String YesterdaySells { get; set; }
        public System.DateTime? created_at { get; set; }
        public System.String product_name { get; set; }
        public System.String full_name { get; set; }
    }

}
// </auto-generated>
