// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class SpClmisHandStockReturnModel
    {
        public System.String product_name { get; set; }
        public System.Int32 stock_id { get; set; }
        public System.Int32? ProjectId { get; set; }
        public System.Int32 product_id { get; set; }
        public System.Int32 quantity { get; set; }
        public System.String notes { get; set; }
        public System.Decimal? Price { get; set; }
        public System.DateTime created_at { get; set; }
        public System.Boolean IsActive { get; set; }
        public System.Int32 regions_id { get; set; }
        public System.String region_name { get; set; }
    }

}
// </auto-generated>
