// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class SpContentpmsReturnModel
    {
        public System.Int32? ProjectId { get; set; }
        public System.Int32 content_id { get; set; }
        public System.String content_name { get; set; }
        public System.String category_name { get; set; }
        public System.String content_name_sindhi { get; set; }
        public System.String content_name_urdu { get; set; }
        public System.String path { get; set; }
        public System.String path_sindhi { get; set; }
        public System.String path_urdu { get; set; }
        public System.Int32 category_id { get; set; }
        public System.String content_type { get; set; }
        public System.DateTime created_at { get; set; }
        public System.Boolean IsActive { get; set; }
    }

}
// </auto-generated>
