// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class SpContinuedUserClientListingCsvReturnModel
    {
        public System.Int32 mwra_id { get; set; }
        public System.Int32 mwraclientId { get; set; }
        public System.String CR_Code { get; set; }
        public System.Int32 mwra_client_id { get; set; }
        public System.String foul { get; set; }
        public System.String pain_lower { get; set; }
        public System.String referral { get; set; }
        public System.String history { get; set; }
        public System.String contraceptual { get; set; }
        public System.Int32? Quantity { get; set; }
        public System.String date_of_starting { get; set; }
        public System.String weight { get; set; }
        public System.String lmp_date { get; set; }
        public System.String date_of_client_generation { get; set; }
        public System.String bp { get; set; }
        public System.String jaundice { get; set; }
        public System.String occasional { get; set; }
        public System.String polar_anemia { get; set; }
        public System.DateTime? created_at { get; set; }
        public System.String name { get; set; }
        public System.String dob { get; set; }
        public System.String address { get; set; }
        public System.String contact_number { get; set; }
        public System.Int32 assigned_marvi_id { get; set; }
        public System.String longitude { get; set; }
        public System.String latitude { get; set; }
        public System.String husband_name { get; set; }
        public System.String cnic { get; set; }
        public System.String maritial_status { get; set; }
        public System.Int32? age { get; set; }
        public System.String occupation { get; set; }
        public System.Int16? is_client { get; set; }
        public System.Int32? region_id { get; set; }
        public System.Int32? taluqa_id { get; set; }
        public System.Int32? union_council_id { get; set; }
        public System.String education_of_class { get; set; }
        public System.String duration_of_marriage { get; set; }
        public System.String crrently_pregnant { get; set; }
        public System.String pregnant_no_of_months { get; set; }
        public System.String no_of_alive_children { get; set; }
        public System.String no_of_abortion { get; set; }
        public System.String no_of_children_died { get; set; }
        public System.String reason_of_death { get; set; }
        public System.String age_of_youngest_child_years { get; set; }
        public System.String age_of_youngest_child_months { get; set; }
        public System.String have_used_fp_method { get; set; }
        public System.String name_of_fp { get; set; }
        public System.String fp_not_used_in_years { get; set; }
        public System.String reason_of_discontinuation { get; set; }
        public System.String fp_no_reason { get; set; }
        public System.String want_to_use_fp { get; set; }
        public System.String fp_purpose { get; set; }
        public System.String is_user_fp { get; set; }
        public System.String fp_method_used { get; set; }
        public System.String date_of_registration { get; set; }
        public System.String full_name { get; set; }
        public System.Boolean IsActive { get; set; }
    }

}
// </auto-generated>
