// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class SpLhvCheckListReturnModel
    {
        public System.Int32 lhv_checklist_id { get; set; }
        public System.Int32? ProjectId { get; set; }
        public System.Int32 app_user_id { get; set; }
        public System.String full_name { get; set; }
        public System.String username { get; set; }
        public System.String region_name { get; set; }
        public System.Int32 visitor_id { get; set; }
        public System.String visitor_name { get; set; }
        public System.DateTime created_at { get; set; }
        public System.String iucd_insertion_kit { get; set; }
        public System.String muac_tape { get; set; }
        public System.String measuring_tape { get; set; }
        public System.String stethoscope { get; set; }
        public System.String bp_apparatus { get; set; }
        public System.String weighing_machcine { get; set; }
        public System.String fetoscope { get; set; }
        public System.String thermometer { get; set; }
        public System.String infection_prevention_kit { get; set; }
        public System.String tablet_with_charger { get; set; }
        public System.String danger_box { get; set; }
        public System.String lhv_apron { get; set; }
        public System.String mec_wheel { get; set; }
        public System.String iucd_insertion_kit_func { get; set; }
        public System.String bp_apparatus_func { get; set; }
        public System.String weighing_func { get; set; }
        public System.String thermometer_func { get; set; }
        public System.String infection_prevention_kit_func { get; set; }
        public System.String tablet_with_charger_func { get; set; }
        public System.String danger_box_func { get; set; }
        public System.String lhv_apron_func { get; set; }
        public System.String provide_counseling_about_fp { get; set; }
        public System.String oral_pills { get; set; }
        public System.String injections { get; set; }
        public System.String iud { get; set; }
        public System.String condoms { get; set; }
        public System.String implant { get; set; }
        public System.String any_natural_method { get; set; }
        public System.String permanent_method { get; set; }
        public System.String any_other { get; set; }
        public System.String provider_use_mec_wheel { get; set; }
        public System.String check_bp { get; set; }
        public System.String check_anemia_and_jaundice { get; set; }
        public System.String measurement_of_weight { get; set; }
        public System.String pelvic_exam { get; set; }
        public System.String client_receive_method_choice { get; set; }
        public System.String explain_how_to_use { get; set; }
        public System.String about_possible_side_effects { get; set; }
        public System.String experience_side_effect { get; set; }
        public System.String follow_up { get; set; }
        public System.String give_tracking_card { get; set; }
        public System.String total_num_of_mwras { get; set; }
        public System.String how_many_verified_by_team { get; set; }
        public System.String remarks1 { get; set; }
        public System.String date { get; set; }
    }

}
// </auto-generated>
