// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class SpMultiProjectAppDetailsReturnModel
    {
        public System.Int32? ProjectId { get; set; }
        public System.String ProjectName { get; set; }
        public System.String PrimaryColor { get; set; }
        public System.String SecoundaryColor { get; set; }
        public System.String HeadingColor { get; set; }
        public System.String SubHeadingColor { get; set; }
        public System.String ProjectImagePath { get; set; }
    }

}
// </auto-generated>
