// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class SPsessionmwraReturnModel
    {
        public System.Int32 session_mwra_id { get; set; }
        public System.DateTime join_datetime { get; set; }
        public System.Int32 session_id { get; set; }
        public System.Int32 mwra_id { get; set; }
        public System.DateTime join_datetime1 { get; set; }
        public System.Boolean IsActive { get; set; }
        public System.String mwra { get; set; }
    }

}
// </auto-generated>
