// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class SpStockListReturnModel
    {
        public System.Int32 product_id { get; set; }
        public System.Int32 user_id { get; set; }
        public System.Int32? ProjectId { get; set; }
        public System.String user_type { get; set; }
        public System.String full_name { get; set; }
        public System.String product_name { get; set; }
        public System.String generic { get; set; }
        public System.String reg_no { get; set; }
        public System.String pack_size { get; set; }
        public System.String path { get; set; }
        public System.Decimal t_p { get; set; }
        public System.Decimal r_p { get; set; }
        public System.String Producttype { get; set; }
        public System.String ProductCategory { get; set; }
        public System.String BrandName { get; set; }
        public System.String MeasurementUnit { get; set; }
        public System.DateTime created_at { get; set; }
        public System.Boolean IsActive { get; set; }
        public System.Int32? quantity { get; set; }
    }

}
// </auto-generated>
