// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class SpTestFpUsersTaluqaTehsilWiseReturnModel
    {
        public System.String taluqa_name { get; set; }
        public System.Int32? NOOR { get; set; }
        public System.Int32? CurrentUser { get; set; }
        public System.Int32? NewUser { get; set; }
        public System.Int32? NewUserCurrentMonth { get; set; }
    }

}
// </auto-generated>
