// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    // stocks
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class Stock : Entity
    {
        public int StockId { get; set; } // stock_id (Primary key)
        public int ProductId { get; set; } // product_id
        public int Quantity { get; set; } // quantity
        public string Notes { get; set; } // notes
        public decimal? Price { get; set; } // Price
        public System.DateTime CreatedAt { get; set; } // created_at
        public bool IsActive { get; set; } // IsActive
        public int? ReturnId { get; set; } // ReturnId
        public int? ProjectId { get; set; } // ProjectId
        public int? RegionId { get; set; } // RegionId

        public Stock()
        {
            CreatedAt = System.DateTime.Now;
            IsActive = true;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
