// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    // users
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class User : Entity
    {
        public int UserId { get; set; } // user_id (Primary key)
        public string FullName { get; set; } // full_name (length: 255)
        public string UserName { get; set; } // user_name (length: 255)
        public string Pwd { get; set; } // pwd (length: 255)
        public string PlainPassword { get; set; } // plain_password (length: 500)
        public string Email { get; set; } // email (length: 255)
        public int RoleId { get; set; } // role_id
        public string Designation { get; set; } // designation (length: 500)
        public System.DateTime CreatedAt { get; set; } // created_at
        public bool IsActive { get; set; } // IsActive
        public int? ProjectId { get; set; } // ProjectId

        // Foreign keys

        /// <summary>
        /// Parent ProjectSolution pointed by [users].([ProjectId]) (FK_users_ProjectSolution)
        /// </summary>
        public virtual ProjectSolution ProjectSolution { get; set; } // FK_users_ProjectSolution

        /// <summary>
        /// Parent Role pointed by [users].([RoleId]) (FK_users_roles)
        /// </summary>
        public virtual Role Role { get; set; } // FK_users_roles

        public User()
        {
            CreatedAt = System.DateTime.Now;
            IsActive = true;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
