// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    // UserMenuAccess
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class UserMenuAccessConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<UserMenuAccess>
    {
        public UserMenuAccessConfiguration()
            : this("dbo")
        {
        }

        public UserMenuAccessConfiguration(string schema)
        {
            ToTable("UserMenuAccess", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.UserId).HasColumnName(@"UserId").HasColumnType("nvarchar").IsRequired().HasMaxLength(128);
            Property(x => x.MenuId).HasColumnName(@"MenuId").HasColumnType("int").IsRequired();
            Property(x => x.AccessLevelId).HasColumnName(@"AccessLevelId").HasColumnType("smallint").IsRequired();
            Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit").IsRequired();

            // Foreign keys
            HasRequired(a => a.AspNetUser).WithMany(b => b.UserMenuAccesses).HasForeignKey(c => c.UserId).WillCascadeOnDelete(false); // FK_UserMenuAccess_AspNetUsers
            HasRequired(a => a.Menu).WithMany(b => b.UserMenuAccesses).HasForeignKey(c => c.MenuId).WillCascadeOnDelete(false); // FK_UserMenuAccess_Menu
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
