// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    // AccessLevel
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class AccessLevel : Entity
    {
        public short Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name (length: 50)
        public bool IsActive { get; set; } // IsActive

        // Reverse navigation

        /// <summary>
        /// Child RoleMenuAccesses where [RoleMenuAccess].[AccessLevelId] point to this entity (FK_RoleMenuAccess_AccessLevel)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<RoleMenuAccess> RoleMenuAccesses { get; set; } // RoleMenuAccess.FK_RoleMenuAccess_AccessLevel

        public AccessLevel()
        {
            RoleMenuAccesses = new System.Collections.Generic.List<RoleMenuAccess>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
