// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    // Api_logs
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class ApiLog : Entity
    {
        public int Id { get; set; } // Id (Primary key)
        public string ApiKey { get; set; } // ApiKey (length: 500)
        public System.DateTime? Timestamp { get; set; } // Timestamp
        public string UsageType { get; set; } // UsageType (length: 500)
        public string Content { get; set; } // Content (length: 1073741823)
        public string Uri { get; set; } // Uri (length: 500)
        public string RequestMethod { get; set; } // RequestMethod (length: 50)
        public string Ip { get; set; } // IP (length: 50)
        public int? StatusCode { get; set; } // StatusCode
        public System.DateTime CreatedAt { get; set; } // created_at
        public bool IsActive { get; set; } // isActive
        public string HeadersSerialized { get; set; } // HeadersSerialized

        public ApiLog()
        {
            CreatedAt = System.DateTime.Now;
            IsActive = true;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
