// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    // The table 'app_users_ppif' is not usable by entity framework because it
    // does not have a primary key. It is listed here for completeness.
    // app_users_ppif
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class AppUsersPpif : Entity
    {
        public double? AppUserId { get; set; } // app_user_id
        public string FullName { get; set; } // full_name (length: 255)
        public string FullNameUrdu { get; set; } // full_name_urdu (length: 255)
        public string FullNameSindhi { get; set; } // full_name_sindhi (length: 255)
        public System.DateTime? Dob { get; set; } // dob
        public double? RegionId { get; set; } // region_id
        public double? TaluqaId { get; set; } // taluqa_id
        public double? UnionCouncilId { get; set; } // union_council_id
        public string Username { get; set; } // username (length: 255)
        public double? Pwd { get; set; } // pwd
        public double? PlainPassword { get; set; } // plain_password
        public string Address { get; set; } // address (length: 255)
        public double? ContactNumber { get; set; } // contact_number
        public string MaritalStatus { get; set; } // marital_status (length: 255)
        public string FatherHusbandName { get; set; } // father_husband_name (length: 255)
        public double? AgePerCnic { get; set; } // age_per_cnic
        public string Cnic { get; set; } // cnic (length: 255)
        public System.DateTime? CnicValidtyEnd { get; set; } // cnic_validty_end
        public string Qualification { get; set; } // qualification (length: 255)
        public double? LhvAssigned { get; set; } // lhv_assigned
        public string ShopName { get; set; } // shop_name (length: 255)
        public double? NoOfNWorkerAssign { get; set; } // no_of_n_worker_assign
        public double? CoordinatesLong { get; set; } // coordinates_long
        public double? CoordinatesLatitude { get; set; } // coordinates_latitude
        public double? TotalMarviAssigned { get; set; } // total_marvi_assigned
        public string UserType { get; set; } // user_type (length: 255)
        public string PopulcationCovered { get; set; } // populcation_covered (length: 255)
        public string NoOfHouseHolds { get; set; } // no_of_house_holds (length: 255)
        public string TargetMwras { get; set; } // target_mwras (length: 255)
        public string NearbyPublicFaculty { get; set; } // nearby_public_faculty (length: 255)
        public string NearbyPrivateFaculty { get; set; } // nearby_private_faculty (length: 255)
        public string DateOfJoin { get; set; } // date_of_join (length: 255)
        public string DateOfTrain { get; set; } // date_of_train (length: 255)
        public string DeviceToken { get; set; } // device_token (length: 255)
        public string NoorCode { get; set; } // noor_code (length: 255)
        public System.DateTime? CreatedAt { get; set; } // created_at

        public AppUsersPpif()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
