// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    // app_users
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class AppUserConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<AppUser>
    {
        public AppUserConfiguration()
            : this("dbo")
        {
        }

        public AppUserConfiguration(string schema)
        {
            ToTable("app_users", schema);
            HasKey(x => x.AppUserId);

            Property(x => x.AppUserId).HasColumnName(@"app_user_id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.FullName).HasColumnName(@"full_name").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.FullNameUrdu).HasColumnName(@"full_name_urdu").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.FullNameSindhi).HasColumnName(@"full_name_sindhi").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.Dob).HasColumnName(@"dob").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.RegionId).HasColumnName(@"region_id").HasColumnType("int").IsOptional();
            Property(x => x.TaluqaId).HasColumnName(@"taluqa_id").HasColumnType("int").IsOptional();
            Property(x => x.UnionCouncilId).HasColumnName(@"union_council_id").HasColumnType("int").IsOptional();
            Property(x => x.Username).HasColumnName(@"username").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.Pwd).HasColumnName(@"pwd").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(500);
            Property(x => x.PlainPassword).HasColumnName(@"plain_password").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(500);
            Property(x => x.Address).HasColumnName(@"address").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.ContactNumber).HasColumnName(@"contact_number").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(15);
            Property(x => x.MaritalStatus).HasColumnName(@"marital_status").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.FatherHusbandName).HasColumnName(@"father_husband_name").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.AgePerCnic).HasColumnName(@"age_per_cnic").HasColumnType("int").IsOptional();
            Property(x => x.Cnic).HasColumnName(@"cnic").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(40);
            Property(x => x.CnicValidtyEnd).HasColumnName(@"cnic_validty_end").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.Qualification).HasColumnName(@"qualification").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.LhvAssigned).HasColumnName(@"lhv_assigned").HasColumnType("int").IsOptional();
            Property(x => x.TotalMarviAssigned).HasColumnName(@"total_marvi_assigned").HasColumnType("int").IsOptional();
            Property(x => x.UserType).HasColumnName(@"user_type").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.PopulcationCovered).HasColumnName(@"populcation_covered").HasColumnType("int").IsOptional();
            Property(x => x.NoOfHouseHolds).HasColumnName(@"no_of_house_holds").HasColumnType("int").IsOptional();
            Property(x => x.TargetMwras).HasColumnName(@"target_mwras").HasColumnType("int").IsOptional();
            Property(x => x.NearbyPublicFaculty).HasColumnName(@"nearby_public_faculty").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.NearbyPrivateFaculty).HasColumnName(@"nearby_private_faculty").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.DateOfJoin).HasColumnName(@"date_of_join").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.DateOfTrain).HasColumnName(@"date_of_train").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.CreatedAt).HasColumnName(@"created_at").HasColumnType("datetime2").IsOptional();
            Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit").IsRequired();
            Property(x => x.RefferredbyMarvi).HasColumnName(@"RefferredbyMarvi").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.DateofClientGeneration).HasColumnName(@"DateofClientGeneration").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.Occasion).HasColumnName(@"Occasion").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.Referral).HasColumnName(@"Referral").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.IncaseOfCurrentUserDateOfStarting).HasColumnName(@"IncaseOfCurrentUserDateOfStarting").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(500);
            Property(x => x.HistoryOfIrregularMenstrualcycle).HasColumnName(@"HistoryOfIrregularMenstrualcycle").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(500);
            Property(x => x.LmpDate).HasColumnName(@"LmpDate").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.Bp).HasColumnName(@"BP").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.Weight).HasColumnName(@"weight").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.Jaundice).HasColumnName(@"jaundice").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.PollarAnemia).HasColumnName(@"PollarAnemia").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.Foulsmellingvaginaldischarge).HasColumnName(@"Foulsmellingvaginaldischarge").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.Painlowerabdomen).HasColumnName(@"Painlowerabdomen").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.Pills).HasColumnName(@"Pills").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.Condoms).HasColumnName(@"Condoms").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.Injectables1Month).HasColumnName(@"Injectables1month").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.Injectables2Month).HasColumnName(@"Injectables2month").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.Injectables3Month).HasColumnName(@"Injectables3month").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.Iucd5Year).HasColumnName(@"IUCD5year").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.Iucd10Year).HasColumnName(@"IUCD10year").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.Implant).HasColumnName(@"Implant").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.Tl).HasColumnName(@"TL").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.Longitude).HasColumnName(@"Longitude").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(500);
            Property(x => x.Latitude).HasColumnName(@"Latitude").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(500);
            Property(x => x.ShopName).HasColumnName(@"ShopName").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.CurrentStatusOfService).HasColumnName(@"currentStatusOfService").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(500);
            Property(x => x.Organization).HasColumnName(@"Organization").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(500);
            Property(x => x.Designation).HasColumnName(@"Designation").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(500);
            Property(x => x.PicturePath).HasColumnName(@"PicturePath").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(500);
            Property(x => x.ClinicName).HasColumnName(@"ClinicName").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(500);
            Property(x => x.PrivateHcp).HasColumnName(@"PrivateHCP").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(500);
            Property(x => x.Email).HasColumnName(@"email").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(500);
            Property(x => x.ProjectId).HasColumnName(@"ProjectId").HasColumnType("int").IsOptional();
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
