// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    // Blmis_userstock
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class BlmisUserstockConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<BlmisUserstock>
    {
        public BlmisUserstockConfiguration()
            : this("dbo")
        {
        }

        public BlmisUserstockConfiguration(string schema)
        {
            ToTable("Blmis_userstock", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.UserId).HasColumnName(@"UserId").HasColumnType("int").IsRequired();
            Property(x => x.ProductId).HasColumnName(@"ProductId").HasColumnType("int").IsRequired();
            Property(x => x.Quantity).HasColumnName(@"Quantity").HasColumnType("int").IsRequired();
            Property(x => x.Price).HasColumnName(@"Price").HasColumnType("money").IsRequired().HasPrecision(19,4);
            Property(x => x.CreatedAt).HasColumnName(@"created_at").HasColumnType("datetime2").IsRequired();
            Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit").IsRequired();
            Property(x => x.LhvId).HasColumnName(@"LhvId").HasColumnType("int").IsOptional();
            Property(x => x.CategoryId).HasColumnName(@"CategoryId").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.Date).HasColumnName(@"date").HasColumnType("datetime").IsOptional();
            Property(x => x.ProjectId).HasColumnName(@"ProjectId").HasColumnType("int").IsOptional();
            Property(x => x.Unit).HasColumnName(@"Unit").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
