// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    // client_checklist
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class ClientChecklistConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ClientChecklist>
    {
        public ClientChecklistConfiguration()
            : this("dbo")
        {
        }

        public ClientChecklistConfiguration(string schema)
        {
            ToTable("client_checklist", schema);
            HasKey(x => x.ClientChecklistId);

            Property(x => x.ClientChecklistId).HasColumnName(@"client_checklist_id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.AppUserId).HasColumnName(@"app_user_id").HasColumnType("int").IsRequired();
            Property(x => x.VisitorId).HasColumnName(@"visitor_id").HasColumnType("int").IsRequired();
            Property(x => x.VisitorName).HasColumnName(@"visitor_name").HasColumnType("nvarchar").IsRequired().HasMaxLength(255);
            Property(x => x.MwraId).HasColumnName(@"mwra_id").HasColumnType("int").IsOptional();
            Property(x => x.CreatedAt).HasColumnName(@"created_at").HasColumnType("datetime2").IsRequired();
            Property(x => x.GetInformation).HasColumnName(@"get_information").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.ReceivePrescribed).HasColumnName(@"receive_prescribed").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.RestartContraceptiveMethod).HasColumnName(@"restart_contraceptive_method").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.GetSupplier).HasColumnName(@"get_supplier").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.SwitchContraceptiveMethod).HasColumnName(@"switch_contraceptive_method").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.DiscussAProblem).HasColumnName(@"discuss_a_problem").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.OtherNonFamily).HasColumnName(@"other_non_family").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.NameOfTheMethod).HasColumnName(@"name_of_the_method").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.DropDownMethodsName).HasColumnName(@"drop_down_methods_name").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.ReceivedMethodOfChoice).HasColumnName(@"received_method_of_choice").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.ForTheMethodYouJustAccept).HasColumnName(@"for_the_method_you_just_accept").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.DidProviderDescribe).HasColumnName(@"did_provider_describe").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.NameFewOfSideEffects).HasColumnName(@"name_few_of_side_effects").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.WhatToDoIfProblem).HasColumnName(@"what_to_do_if_problem").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.WhenFolloupVisit).HasColumnName(@"when_folloup_visit").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.DidYouFeelComfortable).HasColumnName(@"did_you_feel_comfortable").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.DidYouFeelInformation).HasColumnName(@"did_you_feel_information").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.DidYouHaveEnoughPrivacy).HasColumnName(@"did_you_have_enough_privacy").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.DuringVisitTreated).HasColumnName(@"during_visit_treated").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.ProviderEncourage).HasColumnName(@"provider_encourage").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.WhenReceivedMethod).HasColumnName(@"when_received_method").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.ReceivedMethodOfChoiceSupport).HasColumnName(@"received_method_of_choice_support").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.ForTheMethodYouJustAcceptSupport).HasColumnName(@"for_the_method_you_just_accept_support").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.ProviderDescribeSideEffects).HasColumnName(@"provider_describe_side_effects").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.NameSideEffects).HasColumnName(@"name_side_effects").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.WhatToDoIfProblemSupport).HasColumnName(@"what_to_do_if_problem_support").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.ToldWhenToVisit).HasColumnName(@"told_when_to_visit").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.ExperienceAnySideEffects).HasColumnName(@"experience_any_side_effects").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.SatisfyByProviderSupport).HasColumnName(@"satisfy_by_provider_support").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.FeelComfortableToAskQuestions).HasColumnName(@"feel_comfortable_to_ask_questions").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.EnoughPrivacyDuringExam).HasColumnName(@"enough_privacy_during_exam").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.TreatedByProvider).HasColumnName(@"treated_by_provider").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.EncourageAskQuestion).HasColumnName(@"encourage_ask_question").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.FpNeedSpacing).HasColumnName(@"fp_need_spacing").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.AdoptingFpMethod).HasColumnName(@"adopting_fp_method").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.Date).HasColumnName(@"date").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(20);
            Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit").IsRequired();
            Property(x => x.ProjectId).HasColumnName(@"ProjectId").HasColumnType("int").IsOptional();
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
