// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class ClmisTotalMwraReturnModel
    {
        public System.Int32 product_id { get; set; }
        public System.String ProductName { get; set; }
        public System.Int32 user_id { get; set; }
        public System.String LHVName { get; set; }
        public System.Int32? QuantityAssignedToLHV { get; set; }
        public System.Int32? QuantityDistributedToMWRA { get; set; }
        public System.Int32? QuantityReturnToHands { get; set; }
        public System.Int32? QuantityReturnToMiscellenous { get; set; }
        public System.Int32? MwraId { get; set; }
        public System.String MWRAName { get; set; }
    }

}
// </auto-generated>
