// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    // content
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class Content : Entity
    {
        public int ContentId { get; set; } // content_id (Primary key)
        public string ContentName { get; set; } // content_name (length: 255)
        public string ContentNameSindhi { get; set; } // content_name_sindhi (length: 255)
        public string ContentNameUrdu { get; set; } // content_name_urdu (length: 255)
        public string Path { get; set; } // path (length: 255)
        public string PathSindhi { get; set; } // path_sindhi (length: 255)
        public string PathUrdu { get; set; } // path_urdu (length: 255)
        public int CategoryId { get; set; } // category_id
        public string ContentType { get; set; } // content_type (length: 50)
        public string Thumbnail { get; set; } // thumbnail (length: 255)
        public System.DateTime CreatedAt { get; set; } // created_at
        public bool IsActive { get; set; } // IsActive
        public int? ProjectId { get; set; } // ProjectId

        // Reverse navigation

        /// <summary>
        /// Child SessionContents where [SessionContent].[contentId] point to this entity (FK_SessionContent_content)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SessionContent> SessionContents { get; set; } // SessionContent.FK_SessionContent_content

        public Content()
        {
            CreatedAt = System.DateTime.Now;
            IsActive = true;
            SessionContents = new System.Collections.Generic.List<SessionContent>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
