// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    // The table 'Curr_User_PPIF_Temp' is not usable by entity framework because it
    // does not have a primary key. It is listed here for completeness.
    // Curr_User_PPIF_Temp
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class CurrUserPpifTemp : Entity
    {
        public string FullName { get; set; } // full_name (length: 255)
        public double? Contact { get; set; } // contact
        public string Address { get; set; } // address (length: 255)
        public double? NoorId { get; set; } // noor_id
        public string NoorAssigned { get; set; } // noor_assigned (length: 255)
        public double? LhvId { get; set; } // LhvId
        public string LhvEnrolled { get; set; } // LHV_enrolled (length: 255)
        public System.DateTime? ClientGeneration { get; set; } // client_generation
        public System.DateTime? DateOfRegistration { get; set; } // date_of_registration
        public string CrCode { get; set; } // CR_Code (length: 255)
        public string Occasional { get; set; } // occasional (length: 255)
        public string Referral { get; set; } // referral (length: 255)
        public System.DateTime? DateOfStarting { get; set; } // date_of_starting
        public string History { get; set; } // history (length: 255)
        public System.DateTime? LmpDate { get; set; } // lmp_date
        public string Bp { get; set; } // bp (length: 255)
        public double? Weight { get; set; } // weight
        public string Jaundice { get; set; } // jaundice (length: 255)
        public string Pollar { get; set; } // pollar (length: 255)
        public string Foul { get; set; } // foul (length: 255)
        public string PainLower { get; set; } // pain_lower (length: 255)
        public double? ProductId { get; set; } // ProductId
        public string Contraceptive { get; set; } // Contraceptive (length: 255)
        public string CurrentUser { get; set; } // Current User (length: 255)

        public CurrUserPpifTemp()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
