// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    // CurrentMrwa_20210923
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class CurrentMrwa20210923Configuration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<CurrentMrwa20210923>
    {
        public CurrentMrwa20210923Configuration()
            : this("dbo")
        {
        }

        public CurrentMrwa20210923Configuration(string schema)
        {
            ToTable("CurrentMrwa_20210923", schema);
            HasKey(x => x.MwraId);

            Property(x => x.MwraId).HasColumnName(@"MwraId").HasColumnType("bigint").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
