// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class GetClientlistReturnModel
    {
        public class ResultSetModel1
        {
            public System.Int32 mwra_id { get; set; }
            public System.String name { get; set; }
            public System.String dob { get; set; }
            public System.String address { get; set; }
            public System.String contact_number { get; set; }
            public System.Int32 assigned_marvi_id { get; set; }
            public System.String marviName { get; set; }
            public System.String longitude { get; set; }
            public System.String latitude { get; set; }
            public System.String husband_name { get; set; }
            public System.String cnic { get; set; }
            public System.String maritial_status { get; set; }
            public System.Int32? age { get; set; }
            public System.String occupation { get; set; }
            public System.Int16? is_client { get; set; }
            public System.DateTime? created_at { get; set; }
            public System.Int32? region_id { get; set; }
            public System.Int32? taluqa_id { get; set; }
            public System.Int32? union_council_id { get; set; }
            public System.String education_of_class { get; set; }
            public System.String duration_of_marriage { get; set; }
            public System.String crrently_pregnant { get; set; }
            public System.String pregnant_no_of_months { get; set; }
            public System.String no_of_alive_children { get; set; }
            public System.String no_of_abortion { get; set; }
            public System.String no_of_children_died { get; set; }
            public System.String reason_of_death { get; set; }
            public System.String age_of_youngest_child_years { get; set; }
            public System.String age_of_youngest_child_months { get; set; }
            public System.String have_used_fp_method { get; set; }
            public System.String name_of_fp { get; set; }
            public System.String fp_not_used_in_years { get; set; }
            public System.String reason_of_discontinuation { get; set; }
            public System.String fp_no_reason { get; set; }
            public System.String want_to_use_fp { get; set; }
            public System.String fp_purpose { get; set; }
            public System.String is_user_fp { get; set; }
            public System.String fp_method_used { get; set; }
            public System.String date_of_registration { get; set; }
            public System.Boolean IsActive { get; set; }
            public System.Int32? ProjectId { get; set; }
            public System.String region_name { get; set; }
            public System.String taluqa_name { get; set; }
            public System.String union_council_name { get; set; }
        }
        public System.Collections.Generic.List<ResultSetModel1> ResultSet1;

        public class ResultSetModel2
        {
            public System.Int32 app_user_id { get; set; }
            public System.String full_name { get; set; }
            public System.String full_name_urdu { get; set; }
            public System.String full_name_sindhi { get; set; }
            public System.String dob { get; set; }
            public System.Int32? region_id { get; set; }
            public System.Int32? taluqa_id { get; set; }
            public System.Int32? union_council_id { get; set; }
            public System.String username { get; set; }
            public System.String pwd { get; set; }
            public System.String plain_password { get; set; }
            public System.String address { get; set; }
            public System.String contact_number { get; set; }
            public System.String marital_status { get; set; }
            public System.String father_husband_name { get; set; }
            public System.Int32? age_per_cnic { get; set; }
            public System.String cnic { get; set; }
            public System.String cnic_validty_end { get; set; }
            public System.String qualification { get; set; }
            public System.Int32? lhv_assigned { get; set; }
            public System.Int32? total_marvi_assigned { get; set; }
            public System.String user_type { get; set; }
            public System.Int32? populcation_covered { get; set; }
            public System.Int32? no_of_house_holds { get; set; }
            public System.Int32? target_mwras { get; set; }
            public System.String nearby_public_faculty { get; set; }
            public System.String nearby_private_faculty { get; set; }
            public System.String date_of_join { get; set; }
            public System.String date_of_train { get; set; }
            public System.DateTime? created_at { get; set; }
            public System.Boolean IsActive { get; set; }
            public System.String RefferredbyMarvi { get; set; }
            public System.String DateofClientGeneration { get; set; }
            public System.String Occasion { get; set; }
            public System.String Referral { get; set; }
            public System.String IncaseOfCurrentUserDateOfStarting { get; set; }
            public System.String HistoryOfIrregularMenstrualcycle { get; set; }
            public System.String LmpDate { get; set; }
            public System.String BP { get; set; }
            public System.String weight { get; set; }
            public System.String jaundice { get; set; }
            public System.String PollarAnemia { get; set; }
            public System.String Foulsmellingvaginaldischarge { get; set; }
            public System.String Painlowerabdomen { get; set; }
            public System.String Pills { get; set; }
            public System.String Condoms { get; set; }
            public System.String Injectables1month { get; set; }
            public System.String Injectables2month { get; set; }
            public System.String Injectables3month { get; set; }
            public System.String IUCD5year { get; set; }
            public System.String IUCD10year { get; set; }
            public System.String Implant { get; set; }
            public System.String TL { get; set; }
            public System.String Longitude { get; set; }
            public System.String Latitude { get; set; }
            public System.String ShopName { get; set; }
            public System.String currentStatusOfService { get; set; }
            public System.String Organization { get; set; }
            public System.String Designation { get; set; }
            public System.String PicturePath { get; set; }
            public System.String ClinicName { get; set; }
            public System.String PrivateHCP { get; set; }
            public System.String email { get; set; }
            public System.Int32? ProjectId { get; set; }
            public System.String region_name { get; set; }
        }
        public System.Collections.Generic.List<ResultSetModel2> ResultSet2;

        public class ResultSetModel3
        {
            public System.Int32 app_user_id { get; set; }
            public System.String full_name { get; set; }
            public System.String full_name_urdu { get; set; }
            public System.String full_name_sindhi { get; set; }
            public System.String dob { get; set; }
            public System.Int32? region_id { get; set; }
            public System.Int32? taluqa_id { get; set; }
            public System.Int32? union_council_id { get; set; }
            public System.String username { get; set; }
            public System.String pwd { get; set; }
            public System.String plain_password { get; set; }
            public System.String address { get; set; }
            public System.String contact_number { get; set; }
            public System.String marital_status { get; set; }
            public System.String father_husband_name { get; set; }
            public System.Int32? age_per_cnic { get; set; }
            public System.String cnic { get; set; }
            public System.String cnic_validty_end { get; set; }
            public System.String qualification { get; set; }
            public System.Int32? lhv_assigned { get; set; }
            public System.Int32? total_marvi_assigned { get; set; }
            public System.String user_type { get; set; }
            public System.Int32? populcation_covered { get; set; }
            public System.Int32? no_of_house_holds { get; set; }
            public System.Int32? target_mwras { get; set; }
            public System.String nearby_public_faculty { get; set; }
            public System.String nearby_private_faculty { get; set; }
            public System.String date_of_join { get; set; }
            public System.String date_of_train { get; set; }
            public System.DateTime? created_at { get; set; }
            public System.Boolean IsActive { get; set; }
            public System.String RefferredbyMarvi { get; set; }
            public System.String DateofClientGeneration { get; set; }
            public System.String Occasion { get; set; }
            public System.String Referral { get; set; }
            public System.String IncaseOfCurrentUserDateOfStarting { get; set; }
            public System.String HistoryOfIrregularMenstrualcycle { get; set; }
            public System.String LmpDate { get; set; }
            public System.String BP { get; set; }
            public System.String weight { get; set; }
            public System.String jaundice { get; set; }
            public System.String PollarAnemia { get; set; }
            public System.String Foulsmellingvaginaldischarge { get; set; }
            public System.String Painlowerabdomen { get; set; }
            public System.String Pills { get; set; }
            public System.String Condoms { get; set; }
            public System.String Injectables1month { get; set; }
            public System.String Injectables2month { get; set; }
            public System.String Injectables3month { get; set; }
            public System.String IUCD5year { get; set; }
            public System.String IUCD10year { get; set; }
            public System.String Implant { get; set; }
            public System.String TL { get; set; }
            public System.String Longitude { get; set; }
            public System.String Latitude { get; set; }
            public System.String ShopName { get; set; }
            public System.String currentStatusOfService { get; set; }
            public System.String Organization { get; set; }
            public System.String Designation { get; set; }
            public System.String PicturePath { get; set; }
            public System.String ClinicName { get; set; }
            public System.String PrivateHCP { get; set; }
            public System.String email { get; set; }
            public System.Int32? ProjectId { get; set; }
            public System.String region_name { get; set; }
            public System.String taluqa_name { get; set; }
            public System.String union_council_name { get; set; }
        }
        public System.Collections.Generic.List<ResultSetModel3> ResultSet3;

    }

}
// </auto-generated>
