// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class GetFutureSessionDataReturnModel
    {
        public System.Int32 session_id { get; set; }
        public System.DateTime next_session_schedule { get; set; }
        public System.Int16 is_completed { get; set; }
        public System.String longitude { get; set; }
        public System.String latitude { get; set; }
        public System.DateTime session_start_datetime { get; set; }
        public System.DateTime session_end_datetime { get; set; }
        public System.Int16 is_group { get; set; }
        public System.Int32 marvi_id { get; set; }
        public System.Int32 mobile_session_id { get; set; }
        public System.Int32 lhv_id { get; set; }
        public System.String user_type { get; set; }
        public System.DateTime created_at { get; set; }
        public System.String MarviName { get; set; }
        public System.String LhvName { get; set; }
        public System.Int32? MwraCount { get; set; }
        public System.String MWRANames { get; set; }
        public System.Boolean IsActive { get; set; }
    }

}
// </auto-generated>
