// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class GetMwraClienWithNameReturnModel
    {
        public System.String ProductName { get; set; }
        public System.String mwra { get; set; }
        public System.String region_name { get; set; }
        public System.String taluqa_name { get; set; }
        public System.String union_council_name { get; set; }
        public System.Int32? lhvId { get; set; }
        public System.String lhvName { get; set; }
        public System.Int32? marviId { get; set; }
        public System.String marviName { get; set; }
        public System.Int32 MwraClientId { get; set; }
        public System.String Foul { get; set; }
        public System.String PainLower { get; set; }
        public System.String Referral { get; set; }
        public System.String History { get; set; }
        public System.String Contraceptual { get; set; }
        public System.String DateOfStarting { get; set; }
        public System.String Weight { get; set; }
        public System.String LmpDate { get; set; }
        public System.String DateOfClientGeneration { get; set; }
        public System.String Bp { get; set; }
        public System.String Jaundice { get; set; }
        public System.String Occasional { get; set; }
        public System.String PolarAnemia { get; set; }
        public System.Int32? MwraId { get; set; }
        public System.Int32? ProductId { get; set; }
        public System.Int32? Quantity { get; set; }
        public System.DateTime? CreatedAt { get; set; }
        public System.Boolean IsActive { get; set; }
    }

}
// </auto-generated>
