// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    // marvi_lhv
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class MarviLhv : Entity
    {
        public string LhvName { get; set; } // lhv_name (Primary key) (length: 255)
        public string MarviName { get; set; } // marvi_name (Primary key) (length: 255)
        public int MarviId { get; set; } // marviId (Primary key)
        public int RegionId { get; set; } // region_id (Primary key)

        public MarviLhv()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
