// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    // The table 'marvi_ppif_delme' is not usable by entity framework because it
    // does not have a primary key. It is listed here for completeness.
    // marvi_ppif_delme
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class MarviPpifDelme : Entity
    {
        public double? S35No { get; set; } // S#No
        public string RegistrationNo { get; set; } // Registration No (length: 255)
        public string NameOfSupervisorLhv { get; set; } // Name of Supervisor LHV (length: 255)
        public double? LhvId { get; set; } // LHV Id
        public string NameOfMarvi { get; set; } // Name of MARVI (length: 255)
        public string Father47HusbandName { get; set; } // Father/Husband Name (length: 255)
        public string MarritalStatus40MarriedOrSingle41 { get; set; } // Marrital Status (Married or Single) (length: 255)
        public string Designation { get; set; } // Designation (length: 255)
        public double? Cnic { get; set; } // CNIC
        public double? CellNo { get; set; } // Cell no
        public double? Age { get; set; } // Age
        public string Status { get; set; } // Status (length: 255)
        public string Qualification400To1641 { get; set; } // Qualification      (0 to 16) (length: 255)
        public string Address { get; set; } // Address (length: 255)
        public string Village { get; set; } // Village (length: 255)
        public string Taluka { get; set; } // Taluka (length: 255)
        public string Uc { get; set; } // UC (length: 255)
        public string DropoutMonth { get; set; } // Dropout month (length: 255)
        public string DroputReason { get; set; } // Droput reason (length: 255)
        public int? ProjectId { get; set; } // ProjectId

        public MarviPpifDelme()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
