// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    // Menu
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class Menu : Entity
    {
        public int Id { get; set; } // Id (Primary key)
        public string Tittle { get; set; } // Tittle (length: 50)
        public int ParentId { get; set; } // ParentId
        public string Controller { get; set; } // Controller (length: 250)
        public string Action { get; set; } // Action (length: 50)
        public bool IsActive { get; set; } // IsActive

        // Reverse navigation

        /// <summary>
        /// Child RoleMenuAccesses where [RoleMenuAccess].[MenuId] point to this entity (FK_RoleMenuAccess_Menu)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<RoleMenuAccess> RoleMenuAccesses { get; set; } // RoleMenuAccess.FK_RoleMenuAccess_Menu
        /// <summary>
        /// Child UserMenuAccesses where [UserMenuAccess].[MenuId] point to this entity (FK_UserMenuAccess_Menu)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<UserMenuAccess> UserMenuAccesses { get; set; } // UserMenuAccess.FK_UserMenuAccess_Menu

        public Menu()
        {
            IsActive = true;
            UserMenuAccesses = new System.Collections.Generic.List<UserMenuAccess>();
            RoleMenuAccesses = new System.Collections.Generic.List<RoleMenuAccess>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
