// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    // MultiProjectAppDetails
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class MultiProjectAppDetail : Entity
    {
        public int Id { get; set; } // Id (Primary key)
        public int? ProjectId { get; set; } // ProjectId
        public string PrimaryColor { get; set; } // PrimaryColor (length: 255)
        public string SecoundaryColor { get; set; } // SecoundaryColor (length: 255)
        public string HeadingColor { get; set; } // HeadingColor (length: 255)
        public string SubHeadingColor { get; set; } // SubHeadingColor (length: 255)
        public string ProjectImagePath { get; set; } // ProjectImagePath (length: 255)
        public bool IsActive { get; set; } // isActive

        public MultiProjectAppDetail()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
