// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    // ProjectMenuAccess
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class ProjectMenuAccess : Entity
    {
        public int Id { get; set; } // Id (Primary key)
        public int? ProjectId { get; set; } // ProjectId
        public int? MenuId { get; set; } // MenuId
        public bool IsActive { get; set; } // IsActive

        public ProjectMenuAccess()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
