// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    // ProjectSolution
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class ProjectSolution : Entity
    {
        public int Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name (length: 500)
        public bool IsActive { get; set; } // IsActive
        public System.DateTime CreatedAt { get; set; } // created_at
        public string Logo { get; set; } // Logo (length: 255)

        // Reverse navigation

        /// <summary>
        /// Child AssignRoleToProjects where [AssignRoleToProject].[ProjectId] point to this entity (FK_AssignRoleToProject_ProjectSolution)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<AssignRoleToProject> AssignRoleToProjects { get; set; } // AssignRoleToProject.FK_AssignRoleToProject_ProjectSolution
        /// <summary>
        /// Child Users where [users].[ProjectId] point to this entity (FK_users_ProjectSolution)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<User> Users { get; set; } // users.FK_users_ProjectSolution

        public ProjectSolution()
        {
            IsActive = true;
            CreatedAt = System.DateTime.Now;
            Users = new System.Collections.Generic.List<User>();
            AssignRoleToProjects = new System.Collections.Generic.List<AssignRoleToProject>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
