// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    // The table 'session_ppif' is not usable by entity framework because it
    // does not have a primary key. It is listed here for completeness.
    // session_ppif
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class SessionPpif : Entity
    {
        public double? SessionId { get; set; } // session_id
        public string NextSessionSchedule { get; set; } // next_session_schedule (length: 255)
        public double? IsCompleted { get; set; } // is_completed
        public double? Longitude { get; set; } // longitude
        public double? Latitude { get; set; } // latitude
        public System.DateTime? SessionStartDatetime { get; set; } // session_start_datetime
        public System.DateTime? SessionEndDatetime { get; set; } // session_end_datetime
        public double? IsGroup { get; set; } // is_group
        public double? MarviId { get; set; } // marvi_id
        public double? MobileSessionId { get; set; } // mobile_session_id
        public double? LhvId { get; set; } // lhv_id
        public string UserType { get; set; } // user_type (length: 255)
        public System.DateTime? CreatedAt { get; set; } // created_at
        public string DbLhvid { get; set; } // db_lhvid (length: 255)
        public string DbMarviId { get; set; } // db_marvi_id (length: 255)

        public SessionPpif()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
