// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    // SessionContent
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class SessionContent : Entity
    {
        public int Id { get; set; } // Id (Primary key)
        public int? SessionId { get; set; } // sessionId
        public int? ContentId { get; set; } // contentId
        public bool IsActive { get; set; } // IsActive
        public int? ProjectId { get; set; } // ProjectId

        // Foreign keys

        /// <summary>
        /// Parent Content pointed by [SessionContent].([ContentId]) (FK_SessionContent_content)
        /// </summary>
        public virtual Content Content { get; set; } // FK_SessionContent_content

        /// <summary>
        /// Parent Session pointed by [SessionContent].([SessionId]) (FK_SessionContent_session)
        /// </summary>
        public virtual Session Session { get; set; } // FK_SessionContent_session

        public SessionContent()
        {
            IsActive = true;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
