// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    // session_followup
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class SessionFollowup : Entity
    {
        public int SessionFollowupId { get; set; } // session_followup_id (Primary key)
        public string Foul { get; set; } // foul (length: 20)
        public string Advise { get; set; } // advise (length: 255)
        public string PainLower { get; set; } // pain_lower (length: 20)
        public string Danger { get; set; } // danger (length: 20)
        public int? Weight { get; set; } // weight
        public System.DateTime? LmpDate { get; set; } // lmp_date
        public string Complication { get; set; } // complication (length: 20)
        public string Bp { get; set; } // bp (length: 20)
        public string Jaundice { get; set; } // jaundice (length: 20)
        public string HistoryIrregular { get; set; } // history_irregular (length: 20)
        public string PolarAnemia { get; set; } // polar_anemia (length: 20)
        public int SessionId { get; set; } // session_id
        public int LhvId { get; set; } // lhv_id
        public int MarviId { get; set; } // marvi_id
        public int MwraId { get; set; } // mwra_id
        public string Referral { get; set; } // referral (length: 50)
        public string Occasional { get; set; } // occasional (length: 50)
        public int? ProductId { get; set; } // ProductId
        public int? Quantity { get; set; } // Quantity
        public System.DateTime CreatedAt { get; set; } // created_at
        public bool IsActive { get; set; } // IsActive
        public int? ProjectId { get; set; } // ProjectId
        public System.DateTime? DateOfFollowup { get; set; } // date_of_followup
        public System.DateTime? DeviceCreatedDate { get; set; } // DeviceCreatedDate

        public SessionFollowup()
        {
            CreatedAt = System.DateTime.Now;
            IsActive = true;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
