// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    // The table 'session_inventory_ppif' is not usable by entity framework because it
    // does not have a primary key. It is listed here for completeness.
    // session_inventory_ppif
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class SessionInventoryPpif : Entity
    {
        public double? SessionInventoryId { get; set; } // session_inventory_id
        public double? SessionId { get; set; } // session_id
        public string ProductName { get; set; } // product_name (length: 255)
        public double? ProductId { get; set; } // product_id
        public double? ProductQty { get; set; } // product_qty
        public double? MarviId { get; set; } // marvi_id
        public System.DateTime? CreatedAt { get; set; } // created_at
        public string DbSessionId { get; set; } // db_session_id (length: 255)
        public string DbUserId { get; set; } // db_user_id (length: 255)
        public double? DbProdId { get; set; } // db_prod_id

        public SessionInventoryPpif()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
