// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    // SessionInventory
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class SessionInventory : Entity
    {
        public int Id { get; set; } // Id (Primary key)
        public int? SessionId { get; set; } // SessionId
        public int? ProductId { get; set; } // ProductId
        public int? Quantity { get; set; } // Quantity
        public int? UserId { get; set; } // UserId
        public int? MwraId { get; set; } // MwraId
        public bool IsActive { get; set; } // IsActive
        public System.DateTime CreatedDate { get; set; } // createdDate
        public int? MwraClientId { get; set; } // mwra_client_id
        public int? FollowupId { get; set; } // FollowupId
        public int? ReturnId { get; set; } // ReturnId
        public int? ProjectId { get; set; } // projectId
        public int? RegionId { get; set; } // RegionId

        public SessionInventory()
        {
            IsActive = true;
            CreatedDate = System.DateTime.Now;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
