// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    // The table 'session_mwras_ppif' is not usable by entity framework because it
    // does not have a primary key. It is listed here for completeness.
    // session_mwras_ppif
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class SessionMwrasPpif : Entity
    {
        public double? SessionMwraId { get; set; } // session_mwra_id
        public double? SessionId { get; set; } // session_id
        public double? MwraId { get; set; } // mwra_id
        public System.DateTime? JoinDatetime { get; set; } // join_datetime
        public string MwraName { get; set; } // Mwra_Name (length: 255)
        public string MwraHusbandName { get; set; } // Mwra_Husband_Name (length: 255)
        public double? MwraMarvi { get; set; } // Mwra_Marvi
        public string DbSessionId { get; set; } // Db_session_id (length: 255)

        public SessionMwrasPpif()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
