// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    // session
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class SessionConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Session>
    {
        public SessionConfiguration()
            : this("dbo")
        {
        }

        public SessionConfiguration(string schema)
        {
            ToTable("session", schema);
            HasKey(x => x.SessionId);

            Property(x => x.SessionId).HasColumnName(@"session_id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.NextSessionSchedule).HasColumnName(@"next_session_schedule").HasColumnType("date").IsRequired();
            Property(x => x.IsCompleted).HasColumnName(@"is_completed").HasColumnType("smallint").IsRequired();
            Property(x => x.Longitude).HasColumnName(@"longitude").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(20);
            Property(x => x.Latitude).HasColumnName(@"latitude").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(20);
            Property(x => x.SessionStartDatetime).HasColumnName(@"session_start_datetime").HasColumnType("datetime2").IsRequired();
            Property(x => x.SessionEndDatetime).HasColumnName(@"session_end_datetime").HasColumnType("datetime2").IsRequired();
            Property(x => x.IsGroup).HasColumnName(@"is_group").HasColumnType("smallint").IsRequired();
            Property(x => x.MarviId).HasColumnName(@"marvi_id").HasColumnType("int").IsRequired();
            Property(x => x.MobileSessionId).HasColumnName(@"mobile_session_id").HasColumnType("int").IsRequired();
            Property(x => x.LhvId).HasColumnName(@"lhv_id").HasColumnType("int").IsRequired();
            Property(x => x.UserType).HasColumnName(@"user_type").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.CreatedAt).HasColumnName(@"created_at").HasColumnType("datetime2").IsRequired();
            Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit").IsRequired();
            Property(x => x.ProjectId).HasColumnName(@"ProjectId").HasColumnType("int").IsOptional();
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
