// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class SpBlmisUserStockReturnModel
    {
        public System.Int32 Id { get; set; }
        public System.Int32 UserId { get; set; }
        public System.Int32 ProductId { get; set; }
        public System.Int32 Quantity { get; set; }
        public System.Decimal Price { get; set; }
        public System.DateTime created_at { get; set; }
        public System.Int32? LhvId { get; set; }
        public System.String user_type { get; set; }
        public System.String product_name { get; set; }
        public System.String full_name { get; set; }
        public System.String lhvName { get; set; }
        public System.String Category { get; set; }
        public System.Boolean IsActive { get; set; }
    }

}
// </auto-generated>
