// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class SpClientCheckListReturnModel
    {
        public System.Int32 client_checklist_id { get; set; }
        public System.Int32? ProjectId { get; set; }
        public System.Int32 app_user_id { get; set; }
        public System.Int32? clientId { get; set; }
        public System.String full_name { get; set; }
        public System.String region_name { get; set; }
        public System.String taluqa_name { get; set; }
        public System.String union_council_name { get; set; }
        public System.Int32 visitor_id { get; set; }
        public System.String visitor_name { get; set; }
        public System.DateTime created_at { get; set; }
        public System.String get_information { get; set; }
        public System.String receive_prescribed { get; set; }
        public System.String restart_contraceptive_method { get; set; }
        public System.String get_supplier { get; set; }
        public System.String switch_contraceptive_method { get; set; }
        public System.String discuss_a_problem { get; set; }
        public System.String other_non_family { get; set; }
        public System.String name_of_the_method { get; set; }
        public System.String drop_down_methods_name { get; set; }
        public System.String received_method_of_choice { get; set; }
        public System.String for_the_method_you_just_accept { get; set; }
        public System.String did_provider_describe { get; set; }
        public System.String name_few_of_side_effects { get; set; }
        public System.String what_to_do_if_problem { get; set; }
        public System.String when_folloup_visit { get; set; }
        public System.String did_you_feel_comfortable { get; set; }
        public System.String did_you_feel_information { get; set; }
        public System.String did_you_have_enough_privacy { get; set; }
        public System.String during_visit_treated { get; set; }
        public System.String provider_encourage { get; set; }
        public System.String when_received_method { get; set; }
        public System.String received_method_of_choice_support { get; set; }
        public System.String for_the_method_you_just_accept_support { get; set; }
        public System.String provider_describe_side_effects { get; set; }
        public System.String name_side_effects { get; set; }
        public System.String what_to_do_if_problem_support { get; set; }
        public System.String told_when_to_visit { get; set; }
        public System.String experience_any_side_effects { get; set; }
        public System.String satisfy_by_provider_support { get; set; }
        public System.String feel_comfortable_to_ask_questions { get; set; }
        public System.String enough_privacy_during_exam { get; set; }
        public System.String treated_by_provider { get; set; }
        public System.String encourage_ask_question { get; set; }
        public System.String fp_need_spacing { get; set; }
        public System.String adopting_fp_method { get; set; }
        public System.String date { get; set; }
    }

}
// </auto-generated>
