// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class SpGetProjectDetailsReturnModel
    {
        public System.Int32 Id { get; set; }
        public System.String Name { get; set; }
        public System.Int32 role_id { get; set; }
        public System.String role_name { get; set; }
        public System.Int32 user_id { get; set; }
        public System.String email { get; set; }
        public System.String pwd { get; set; }
    }

}
// </auto-generated>
