// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class SpMissedSessionDateReturnModel
    {
        public System.Int32 session_id { get; set; }
        public System.DateTime next_session_schedule { get; set; }
        public System.Int32? session_id1 { get; set; }
        public System.DateTime? session_start_datetime { get; set; }
        public System.DateTime created_at { get; set; }
        public System.String user_type { get; set; }
        public System.String lhv { get; set; }
        public System.String marvi { get; set; }
        public System.String mwraNames { get; set; }
    }

}
// </auto-generated>
