// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class SpMwraWithMwraclientReturnModel
    {
        public System.Int32 MwraId { get; set; }
        public System.String Name { get; set; }
        public System.String Dob { get; set; }
        public System.String Address { get; set; }
        public System.String ContactNumber { get; set; }
        public System.Int32 AssignedMarviId { get; set; }
        public System.String Longitude { get; set; }
        public System.String Latitude { get; set; }
        public System.String HusbandName { get; set; }
        public System.String Cnic { get; set; }
        public System.String MaritialStatus { get; set; }
        public System.Int32? Age { get; set; }
        public System.String Occupation { get; set; }
        public System.Int16? IsClient { get; set; }
        public System.DateTime? CreatedAt { get; set; }
        public System.Int32? RegionId { get; set; }
        public System.Int32? TaluqaId { get; set; }
        public System.Int32? UnionCouncilId { get; set; }
        public System.String EducationOfClass { get; set; }
        public System.String DurationOfMarriage { get; set; }
        public System.String CrrentlyPregnant { get; set; }
        public System.String PregnantNoOfMonths { get; set; }
        public System.String NoOfAliveChildren { get; set; }
        public System.String NoOfAbortion { get; set; }
        public System.String NoOfChildrenDied { get; set; }
        public System.String ReasonOfDeath { get; set; }
        public System.String AgeOfYoungestChildYears { get; set; }
        public System.String AgeOfYoungestChildMonths { get; set; }
        public System.String HaveUsedFpMethod { get; set; }
        public System.String NameOfFp { get; set; }
        public System.String FpNotUsedInYears { get; set; }
        public System.String ReasonOfDiscontinuation { get; set; }
        public System.String FpNoReason { get; set; }
        public System.String WantToUseFp { get; set; }
        public System.String FpPurpose { get; set; }
        public System.String IsUserFp { get; set; }
        public System.String FpMethodUsed { get; set; }
        public System.String DateOfRegistration { get; set; }
        public System.Boolean IsActive { get; set; }
        public System.String lhvName { get; set; }
        public System.String marviName { get; set; }
        public System.String union_council_name { get; set; }
        public System.String taluqa_name { get; set; }
        public System.String region_name { get; set; }
        public System.Int32? mwra_client_id { get; set; }
        public System.String foul { get; set; }
        public System.String pain_lower { get; set; }
        public System.String referral { get; set; }
        public System.String history { get; set; }
        public System.String contraceptual { get; set; }
        public System.String date_of_starting { get; set; }
        public System.String weight { get; set; }
        public System.String lmp_date { get; set; }
        public System.String date_of_client_generation { get; set; }
        public System.String bp { get; set; }
        public System.String jaundice { get; set; }
        public System.String occasional { get; set; }
        public System.String polar_anemia { get; set; }
        public System.Int32? mwra_id { get; set; }
        public System.Int32? ProductId { get; set; }
        public System.Int32? Quantity { get; set; }
        public System.DateTime? created_at { get; set; }
        public System.Boolean? IsActive1 { get; set; }
        public System.String product_name { get; set; }
    }

}
// </auto-generated>
