// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class SpTestDetailsOfShiftedClientsReturnModel
    {
        public System.String Product { get; set; }
        public System.Int32? Pills { get; set; }
        public System.Int32? Condom { get; set; }
        public System.Int32? Injection { get; set; }
        public System.Int32? IUCD { get; set; }
        public System.Int32? TL { get; set; }
        public System.Int32? Total { get; set; }
    }

}
// </auto-generated>
