// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class SpTrendAmongCurrentUsersReturnModel
    {
        public System.String Injection { get; set; }
        public System.String IUCD { get; set; }
        public System.String Natural { get; set; }
        public System.String Condom { get; set; }
        public System.String Pills { get; set; }
        public System.String TL { get; set; }
        public System.String Implant { get; set; }
        public System.String lhvName { get; set; }
        public System.String lhvId { get; set; }
    }

}
// </auto-generated>
