// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    // stocks
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class StockConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Stock>
    {
        public StockConfiguration()
            : this("dbo")
        {
        }

        public StockConfiguration(string schema)
        {
            ToTable("stocks", schema);
            HasKey(x => x.StockId);

            Property(x => x.StockId).HasColumnName(@"stock_id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.ProductId).HasColumnName(@"product_id").HasColumnType("int").IsRequired();
            Property(x => x.Quantity).HasColumnName(@"quantity").HasColumnType("int").IsRequired();
            Property(x => x.Notes).HasColumnName(@"notes").HasColumnType("varchar(max)").IsRequired().IsUnicode(false);
            Property(x => x.Price).HasColumnName(@"Price").HasColumnType("money").IsOptional().HasPrecision(19,4);
            Property(x => x.CreatedAt).HasColumnName(@"created_at").HasColumnType("datetime2").IsRequired();
            Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit").IsRequired();
            Property(x => x.ReturnId).HasColumnName(@"ReturnId").HasColumnType("int").IsOptional();
            Property(x => x.ProjectId).HasColumnName(@"ProjectId").HasColumnType("int").IsOptional();
            Property(x => x.RegionId).HasColumnName(@"RegionId").HasColumnType("int").IsOptional();
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
