// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    // tempLogs
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class TempLog : Entity
    {
        public int LogId { get; set; } // log_id (Primary key)
        public string Description { get; set; } // description
        public string UserType { get; set; } // user_type (length: 20)
        public int? UserId { get; set; } // user_id
        public string Duration { get; set; } // Duration (length: 50)
        public bool? IsComplete { get; set; } // IsComplete
        public System.DateTime? CreatedAt { get; set; } // created_at
        public bool? IsActive { get; set; } // IsActive
        public int? ProjectId { get; set; } // ProjectId

        public TempLog()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
