// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    // The table 'UN_Temp' is not usable by entity framework because it
    // does not have a primary key. It is listed here for completeness.
    // UN_Temp
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class UnTemp : Entity
    {
        public double? UnionCouncilId { get; set; } // union_council_id
        public string UnionCouncilName { get; set; } // union_council_name (length: 255)
        public double? TaluqaId { get; set; } // taluqa_id
        public System.DateTime? CreatedAt { get; set; } // created_at

        public UnTemp()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
