// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Hands.Data.HandsDB
{

    // UserMenuAccess
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class UserMenuAccess : Entity
    {
        public int Id { get; set; } // Id (Primary key)
        public string UserId { get; set; } // UserId (length: 128)
        public int MenuId { get; set; } // MenuId
        public short AccessLevelId { get; set; } // AccessLevelId
        public bool IsActive { get; set; } // IsActive

        // Foreign keys

        /// <summary>
        /// Parent AspNetUser pointed by [UserMenuAccess].([UserId]) (FK_UserMenuAccess_AspNetUsers)
        /// </summary>
        public virtual AspNetUser AspNetUser { get; set; } // FK_UserMenuAccess_AspNetUsers

        /// <summary>
        /// Parent Menu pointed by [UserMenuAccess].([MenuId]) (FK_UserMenuAccess_Menu)
        /// </summary>
        public virtual Menu Menu { get; set; } // FK_UserMenuAccess_Menu

        public UserMenuAccess()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
