//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hands.Web.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AAAAn21OnYc:APA91bHFVPFzjZI2Ozwrrkg3f8At3PnMCD6zfW0fOTwlwz1ZEjS7n8AUh8FlMuD_EMnW_" +
            "8fR6zMAEAgLJLjcdRLfSFtSYIpuyvrAVPwWM379Qz7bDOEpQf8skGd5sdyyjY4ulfXItQ8z5fdtWKGvQ" +
            "")]
        public string GoogleApplicationId {
            get {
                return ((string)(this["GoogleApplicationId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Password=sa1234!;Persist Security Info=True;User ID=sa;Initial Catalog=handsdbMul" +
            "iprojectOne;Data Source=37.187.132.139,49158\\sqlexpress;")]
        public string HandsDBConnection {
            get {
                return ((string)(this["HandsDBConnection"]));
            }
        }
    }
}
